/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register


/dashboard:
  controller: admin
  action: dashboard

/users:
  controller: admin
  action: getuserslist

/user/delete:
  controller: admin
  action: deleteUserById

/user/update:
  controller: admin
  action: updateUserForm

