/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/forgot-password:
  controller: user
  action: forgotPassword

/forgot-password/{id}:
  controller: user
  action: mailSent

/forgot-password/r/{id}:
  controller: user
  action: tokenCheck

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: dashboard

/pages:
  controller: post
  action: pages

/pages/{id}:
  controller: post
  action: showPage

/pages/{id}/update:
  controller: post
  action: postCheck

/pages/{id}/delete:
  controller: post
  action: postCheck

/post-check:
  controller: post
  action: postCheck
  
/users:
  controller: admin
  action: getUserList

/users/{id}:
  controller: user
  action: show

/users/{id}/delete:
  controller: user
  action: delete

/users/{id}/update:
  controller: user
  action: update
