/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: dashboard


/testmail:
  controller: mail
  action: mail

# Posts
## Pages
/pages:
  controller: post
  action: pages

/pages/{id}:
  controller: post
  action: showPage

/pages/{id}/update:
  controller: post
  action: postCheck

/pages/{id}/delete:
  controller: post
  action: postCheck

## Articles
/articles:
  controller: post
  action: articles

/articles/{id}:
  controller: post
  action: showArticle

/articles/{id}/update:
  controller: post
  action: postCheck

/articles/{id}/delete:
  controller: post
  action: postCheck

/post-check:
  controller: post
  action: postCheck
  
/users:
  controller: admin
  action: getUserList

/users/{id}:
  controller: user
  action: show

/users/{id}/delete:
  controller: user
  action: delete

/users/{id}/update:
  controller: user
  action: update


/forgetPassword:
  controller: user
  action: forgetPassword

