/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register


/dashboard:
  controller: admin
  action: dashboard

/users:
  controller: admin
  action: getuserslist

/user/delete/12:
  controller: admin
  action: deleteUserById

/user/update?id=33:
  controller: admin
  action: updateUserById