/:
  controller: general
  action: home

/me-contacter:
  controller: general
  action: contact

/login:
  controller: user
  action: login

/forgot-password:
  controller: user
  action: forgotPassword

/forgot-password/{id}:
  controller: user
  action: mailSent

/forgot-password/r/{id}:
  controller: user
  action: tokenCheck

/logout:
  controller: user
  action: logout

/register:
  controller: user
  action: register

/dashboard:
  controller: admin
  action: dashboard


/testmail:
  controller: mail
  action: mail

# Posts
## Pages
/pages:
  controller: post
  action: pages

/pages/{id}:
  controller: post
  action: showPage

/pages/{id}/update:
  controller: post
  action: postCheck

/pages/{id}/delete:
  controller: post
  action: postCheck

## Articles
/articles:
  controller: post
  action: articles

/articles/{id}:
  controller: post
  action: showArticle

/articles/{id}/update:
  controller: post
  action: postCheck

/articles/{id}/delete:
  controller: post
  action: postCheck

  ## Tags
/tags:
  controller: post
  action: tags

/tags/{id}:
  controller: post
  action: showTag

/tags/{id}/update:
  controller: post
  action: postCheck

/tags/{id}/delete:
  controller: post
  action: postCheck

/post-check:
  controller: post
  action: postCheck
  
/users:
  controller: admin
  action: getUserList

/users/{id}:
  controller: user
  action: show

/users/{id}/delete:
  controller: user
  action: delete

/users/{id}/update:
  controller: user
  action: update

/front-pages:
  controller: post
  action: getPagesListFront

/front-articles:
  controller: post
  action: getArticlesListFront

/post/{id}:
  controller: post
  action: getOnePostFront
